### ISSUE TITLE
Unable to publish a new NPM package to Google Artifact Registry from Windows Terminal

### ISSUE THREAD

**Issue by evildead** [GoogleCloudPlatform/artifact-registry-npm-tools#27]
I was trying to publish a NPM package to Google Artifact Registry, by thoroughly following the instructions found [here](https://www.npmjs.com/package/google-artifactregistry-auth)

I use:
  * the [Windows Terminal](https://www.microsoft.com/it-it/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)
  * Node.js `v14.17.6`
  * NPM `6.14.15`

I correctly logged in to Google Cloud with my user:
  * `gcloud auth application-default login`
  * `gcloud auth login`

and I correctly put the output of
  > `gcloud artifacts print-settings npm ...`

to a `.npmrc` file inside my project

Everytime I executed:
  > `npx google-artifactregistry-auth`

I received this output:
```
npx: installed 47 in <some>s
Retrieving application default credentials...
Success!
```

But when I tried to publish the NPM package with
  > `npm publish`

I always received a `403 Forbidden` error message like stated in this [Stackoverflow page](https://stackoverflow.com/questions/63177165/unable-to-npm-publish-new-package-to-artifact-registry-even-though-my-logged-in) by another guy who had my same issue

When I checked my `.npmrc` in my user folder, I discovered that no `_authToken` was produced for my private NPM repo.

By repeating the same procedure under Linux Wsl2 (I used this [Install Node.js in Linux Wsl](https://docs.microsoft.com/it-it/windows/dev-environment/javascript/nodejs-on-wsl) to install Node and NPM), the [Google Artifact Registry Auth](https://www.npmjs.com/package/google-artifactregistry-auth) was correctly able to retrieve the `_authToken` and save it to the `.npmrc` in my user folder.

Only then I was able to perform:
  > `npm publish`

Could you please check if you're able to reproduce such an issue for Windows platforms?

Thank you in advance

**Comment by yihanzhen** [comment]
Yes it could be possible. If you have a password config in the user npmrc, the plugin won't generate an auth token for this registry. The reason is that a password of a service account is a legit way to authenticate with Artifact Registry, and _usually_ there's no way that the plugin knows whether the password config is intended or accidentally added there.

Though I guess in your case it should be reasonable to assume an "empty" password config is added by mistake, I think it might be safer not to "play smart" here, given that overwriting the user config is irreversible.

Thanks for your feedback. I'm going to close the issue, but feel free to continue to share your thoughts here.
